name: dart_chromecast
version: 0.2.5
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.4.2
  cli_util: ^0.4.0
  http: ^1.1.0
  logging: ^1.2.0
  multicast_dns: ^0.3.2+3
  protobuf: ^3.1.0
  protoc_plugin:
    git:
      url: https://github.com/google/protobuf.dart
      path: protoc_plugin
  xml: ^6.3.0
