name: dart_chromecast
version: 0.2.5
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: ^2.0.0
  protoc_plugin: 20.0.0
  http: ^0.13.0
  cli_util: ^0.3.0 
  args: ^2.0.0
  xml: ^5.0.2
  observable: ^0.22.2
  logging: ^1.0.0
  multicast_dns: ^0.2.2
dependency_overrides:
  dart_internal: ^0.2.0